import 'package:cloud_storage/resource/strings.dart';

class ApiUrl {
  static String login = APP_URL + 'api/login';
  static String ubahPass = APP_URL + 'api/change_password';
  static String register = APP_URL + 'api/register';
  static String logout = APP_URL + 'api/logout';
  static String language = APP_URL + 'api/language';
  static String genre = APP_URL + 'api/genre';
  static String label = APP_URL + 'api/label';
  static String labelReq = APP_URL + 'api/label_additem';
  static String labelTransaksi = APP_URL + 'api/label_request';
  static String roles = APP_URL + 'api/roletrack';
  static String publishing = APP_URL + 'api/publishing';
  static String saveAlbum = APP_URL + 'api/album_api';
  static String editAlbum = APP_URL + 'api/album_api/';
  static String editAudio = APP_URL + 'api/ringtone_api/';
  static String saveRingtone = APP_URL + 'api/ringtone_api';
  static String saveTrack = APP_URL + 'api/track_api';
  static String editTrack = APP_URL + 'api/track_api/';
  static String saveVideo = APP_URL + 'api/video_api';
  static String editVideo = APP_URL + 'api/video_api/';
  static String getAlbum = APP_URL + 'api/album_api';
  static String getRingtone = APP_URL + 'api/ringtone_api';
  static String getTrack = APP_URL + 'api/track_api';
  static String getVideo = APP_URL + 'api/video_api';
  static String getBank = APP_URL + 'api/bank';
  static String detailsAlbum = APP_URL + 'api/album_api/';
  static String detailsRingtone = APP_URL + 'api/ringtone_api/';
  static String detailsTrack = APP_URL + 'api/track_api/';
  static String detailsVideo = APP_URL + 'api/video_api/';
  static String getGrafik = APP_URL + 'api/dashboard/grafik-bulanan';
  static String countAlbum = APP_URL + 'api/dashboard/count-album';
  static String countTrack = APP_URL + 'api/dashboard/count-track';
  static String countRingtone = APP_URL + 'api/dashboard/count-ringtone';
  static String countVideo = APP_URL + 'api/dashboard/count-video';
  static String countSetup = APP_URL + 'api/dashboard/count-setup';
  static String countAmount = APP_URL + 'api/amount_balance/';
  static String cekReq = APP_URL + 'api/cek_request';
  static String saveTransaction = APP_URL + 'api/transaction_api';
  static String getTransaction = APP_URL + 'api/transaction_api';
  static String detailsTransaction = APP_URL + 'api/transaction/';
  static String profile = APP_URL + 'api/profile';
  static String invoice = APP_URL + 'api/invoice/';
}
